#Installation of Numpy

In [ ]:
pip install numpy

In [ ]:
import numpy
print(numpy.__version__)

2.0.2


In [ ]:
import numpy as np

#Creation of Numpy Elements

In [ ]:
a = np.array
print(a)

<built-in function array>


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


#Type functions in Numpy

In [ ]:
a = np.array([1,2,3])
print(a)
#Returns type of an array
print(type(a))
#Returns data types of elements inside the array
print(a.dtype)
#Returns dimensions of numpy array
print(a.ndim)

['hello' '1' 'mno']
<class 'numpy.ndarray'>
<U21
1


In [ ]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

[['sai' '2' '3']
 ['4' '5' '6']
 ['6' '7' '8']
 ['9' '10' '11']]
<class 'numpy.ndarray'>
<U21
2


In [ ]:
a = np.array([1,2,3], complex)
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>
complex128
1


#Sizes and shapes of Numpy

In [ ]:
a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)

6
(1, 6)


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print('Original array')
print(a)

a = a.reshape(2,3)
print('Reshaped array')
print(a)

Original array
[[1 2]
 [3 4]
 [5 6]]
Reshaped array
[[1 2 3]
 [4 5 6]]


#Accessing of elements in Numpy

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[0,1])
print(a[2,1])
print(a[1,1])
print(a[1,0])

[[1 2]
 [3 4]
 [5 6]]
2
6
4
3


#Functions in Numpy

In [ ]:
a = np.array([1,2,3,50,4,45,4])
print(a)
print(a.max())
print(a.min())
print(a.sum())

[ 1  2  3 50  4 45  4]
50
1
109


In [ ]:
# randn --> generates random number between (-1,0,1)

a = np.random.randn(2,4)
print(a)

[[ 0.41660171 -0.89733797  2.1715752  -0.42826289]
 [-2.05119079  2.26213458 -0.49045792 -0.84744799]]


In [ ]:
# Ranging function in numpy --> arange()

print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12).reshape(2,2,3) # --> 2*3, 2*3 (generates 2 matrices)
print(arr)
print('*********************************')
print(arr[0])
print('*********************************')
print(arr[1])
print('*********************************')
print(arr[0][1])
print('*********************************')
print(arr[0][1][2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
*********************************
[[0 1 2]
 [3 4 5]]
*********************************
[[ 6  7  8]
 [ 9 10 11]]
*********************************
[3 4 5]
*********************************
5


In [ ]:
# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.85])
print(arr)
print("Rounding function: ", np.around(arr))
print('*********************************')
print("With decimal:",np.around(arr, 2) )

[12.2     90.12    12.54789 52.85   ]
Rounding function:  [12. 90. 13. 53.]
*********************************
With decimal: [12.2  90.12 12.55 52.85]


In [ ]:
# Numpy Broadcasting

In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a+b
print(c)

[ 3  6  9 12 15 18 21]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a-b
print(c)

[-1 -2 -3 -4 -5 -6 -7]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b
print(c)

[ 2  8 18 32 50 72 98]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([2,4,6,8])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a+b)
print('*********************************')
print(a-b)
print('*********************************')
print(a*b)

In [ ]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print('*********************************')
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print('*********************************')
print(arr1 + arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
*********************************
[[0]
 [1]
 [2]
 [3]
 [4]]
*********************************
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#Pandas

#Installation of Pandas

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

#Pandas Series

In [ ]:
info = np.array(['A','B','C','D','E','F'])
print(info)
a = pd.Series(info)
print(a)

['A' 'B' 'C' 'D' 'E' 'F']
0    A
1    B
2    C
3    D
4    E
5    F
dtype: object


In [ ]:
info = {'x':100,'y':200,'z':300}
a = pd.Series(info)
print(a)

x    100
y    200
z    300
dtype: int64


In [ ]:
arr = [1,2,3,4]
index = ['a','b','c','d']
x = pd.Series(arr,index)
print(x)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
print(x[3])
print(x.index)
print(x.values)
print(x.dtype)
print(x.size)
print(x.shape)
print(len(x))

4
Index(['a', 'b', 'c', 'd'], dtype='object')
[1 2 3 4]
int64
4
(4,)
4


<ipython-input-46-73b66bb5e031>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(x[3])


In [ ]:
a = pd.Series(data = [1,2,3,np.nan], index = [0,1,2,3])
print(a)
print(a.hasnans)

0      1
1      2
2      3
3    100
dtype: int64
False


#DataFrame

In [ ]:
df = pd.DataFrame()
print(df)

In [ ]:
x = ['Python','Pandas']

df = pd.DataFrame(x)
df

In [ ]:
info = {'ID':[101,102,103,104,105],'Department':['MEC','CEC','MPC','BIPC','HEC']}

df = pd.DataFrame(info)
df

In [ ]:
emp = ['Parker','John','Smith','William']
id = [102,107,109,111]

emp_series = pd.Series(emp)
id_series = pd.Series(id)

a = {'Emp':emp_series, 'ID':id_series}
df = pd.DataFrame(a)
df


In [ ]:
info = {'One':pd.Series([1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g']),
       'Two': pd.Series([1,2,3,4,5,6,7,8],index = ['a','b','c','d','e','f','g','h'])}

df = pd.DataFrame(info)
df

In [ ]:
df['Two']

In [ ]:
df['Three'] = df['One'] + df['Two']
df

In [ ]:
del df['One']
df

#loc and iloc

In [ ]:
data = pd.Series(['a','b','c','d'], index = [1,3,5,7])
print(data)
print(data.loc[1])
print(data.iloc[1])

#Additonal Functions


In [ ]:
data = {"Name":['A','B','C','D'],'Age':['25','21','62','41']}
df = pd.DataFrame(data)
print(df.dtypes)
df

In [ ]:
#astype --> convert one datatype into another datatype

df['Age'] = df['Age'].astype(int)
print(df.dtypes)
df

In [ ]:
df.describe()

In [ ]:
data = {'Name':['A','B',np.nan,'D'], 'Age':[25,np.nan,62,41]}
df = pd.DataFrame(data)
df

In [ ]:
df1 = df.dropna()
df1


In [ ]:
df1 = df.fillna(0)
df1

In [ ]:
data = {"Name":['A','B','C','D'],'Age':[25,21,62,41]}
df = pd.DataFrame(data)

df['Age'].replace(25,30, inplace=True)
df

#   Wroking with CSV files
    #open empty Excel file
    #Click on file -> Save as -> (Choose the location of the current .py file)
    #Create a file name & choose the type as CSV (comma delimited)
    #Enter some values in the file

In [ ]:
df = pd.read_csv('Book1.csv')
df

In [ ]:
df.head() #generates first 5 rows

In [ ]:
df.tail() #generates lsat five rows

In [ ]:
df

In [ ]:
df.apply(np.max)

In [ ]:
df.apply(np.min)

In [ ]:
df.sort_values(by = 'AGE')

In [ ]:
df.loc[df.SALARY == 10000]

In [ ]:
df.loc[(df.AGE > 21) & (df.SALARY > 10000),["NAME","AGE"]]