#Installation of Numpy

In [ ]:
pip install numpy

In [ ]:
import numpy
print(numpy.__version__)

2.0.2


In [2]:
import numpy as np

#Creation of Numpy Elements

In [ ]:
a = np.array
print(a)

<built-in function array>


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


#Type functions in Numpy

In [ ]:
a = np.array([1,2,3])
print(a)
#Returns type of an array
print(type(a))
#Returns data types of elements inside the array
print(a.dtype)
#Returns dimensions of numpy array
print(a.ndim)

['hello' '1' 'mno']
<class 'numpy.ndarray'>
<U21
1


In [ ]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

[['sai' '2' '3']
 ['4' '5' '6']
 ['6' '7' '8']
 ['9' '10' '11']]
<class 'numpy.ndarray'>
<U21
2


In [ ]:
a = np.array([1,2,3], complex)
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>
complex128
1


#Sizes and shapes of Numpy

In [ ]:
a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)

6
(1, 6)


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print('Original array')
print(a)

a = a.reshape(2,3)
print('Reshaped array')
print(a)

Original array
[[1 2]
 [3 4]
 [5 6]]
Reshaped array
[[1 2 3]
 [4 5 6]]


#Accessing of elements in Numpy

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[0,1])
print(a[2,1])
print(a[1,1])
print(a[1,0])

[[1 2]
 [3 4]
 [5 6]]
2
6
4
3


#Functions in Numpy

In [ ]:
a = np.array([1,2,3,50,4,45,4])
print(a)
print(a.max())
print(a.min())
print(a.sum())

[ 1  2  3 50  4 45  4]
50
1
109


In [ ]:
# randn --> generates random number between (-1,0,1)

a = np.random.randn(2,4)
print(a)

[[ 0.41660171 -0.89733797  2.1715752  -0.42826289]
 [-2.05119079  2.26213458 -0.49045792 -0.84744799]]


In [ ]:
# Ranging function in numpy --> arange()

print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12).reshape(2,2,3) # --> 2*3, 2*3 (generates 2 matrices)
print(arr)
print('*********************************')
print(arr[0])
print('*********************************')
print(arr[1])
print('*********************************')
print(arr[0][1])
print('*********************************')
print(arr[0][1][2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
*********************************
[[0 1 2]
 [3 4 5]]
*********************************
[[ 6  7  8]
 [ 9 10 11]]
*********************************
[3 4 5]
*********************************
5


In [ ]:
# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.85])
print(arr)
print("Rounding function: ", np.around(arr))
print('*********************************')
print("With decimal:",np.around(arr, 2) )

[12.2     90.12    12.54789 52.85   ]
Rounding function:  [12. 90. 13. 53.]
*********************************
With decimal: [12.2  90.12 12.55 52.85]


In [ ]:
# Numpy Broadcasting

In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a+b
print(c)

[ 3  6  9 12 15 18 21]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a-b
print(c)

[-1 -2 -3 -4 -5 -6 -7]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b
print(c)

[ 2  8 18 32 50 72 98]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([2,4,6,8])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a+b)
print('*********************************')
print(a-b)
print('*********************************')
print(a*b)

In [ ]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print('*********************************')
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print('*********************************')
print(arr1 + arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
*********************************
[[0]
 [1]
 [2]
 [3]
 [4]]
*********************************
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#Pandas

#Installation of Pandas

In [ ]:
pip install pandas

In [3]:
import pandas as pd

#Pandas Series

In [ ]:
info = np.array(['A','B','C','D','E','F'])
print(info)
a = pd.Series(info)
print(a)

['A' 'B' 'C' 'D' 'E' 'F']
0    A
1    B
2    C
3    D
4    E
5    F
dtype: object


In [ ]:
info = {'x':100,'y':200,'z':300}
a = pd.Series(info)
print(a)

x    100
y    200
z    300
dtype: int64


In [ ]:
arr = [1,2,3,4]
index = ['a','b','c','d']
x = pd.Series(arr,index)
print(x)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
print(x[3])
print(x.index)
print(x.values)
print(x.dtype)
print(x.size)
print(x.shape)
print(len(x))

4
Index(['a', 'b', 'c', 'd'], dtype='object')
[1 2 3 4]
int64
4
(4,)
4


<ipython-input-46-73b66bb5e031>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(x[3])


In [ ]:
a = pd.Series(data = [1,2,3,np.nan], index = [0,1,2,3])
print(a)
print(a.hasnans)

0      1
1      2
2      3
3    100
dtype: int64
False


#DataFrame

In [5]:
df = pd.DataFrame()
print(df)
df

Empty DataFrame
Columns: []
Index: []


Empty DataFrame
Columns: []
Index: []

In [6]:
x = ['Python','Pandas']

df = pd.DataFrame(x)
df

0
0  Python
1  Pandas

In [17]:
info = {'ID':[101,102,103,104,105],'Department':['MEC','CEC','MPC','BIPC','HEC']}

df = pd.DataFrame(info)
df

ID Department
0  101        MEC
1  102        CEC
2  103        MPC
3  104       BIPC
4  105        HEC

In [8]:
emp = ['Parker','John','Smith','William']
id = [102,107,109,111]

emp_series = pd.Series(emp)
id_series = pd.Series(id)

a = {'Emp':emp_series, 'ID':id_series}
df = pd.DataFrame(a)
df


Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  William  111

In [18]:
info = {'One':pd.Series([1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g']),
       'Two': pd.Series([1,2,3,4,5,6,7,8],index = ['a','b','c','d','e','f','g','h'])}

df = pd.DataFrame(info)
df

One  Two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  7.0    7
h  NaN    8

In [12]:
df['Two']

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
Name: Two, dtype: int64

In [14]:
df['Three'] = df['One'] + df['Two']
df

One  Two  Three
a  1.0    1    0.0
b  2.0    2    0.0
c  3.0    3    0.0
d  4.0    4    0.0
e  5.0    5    0.0
f  6.0    6    0.0
g  7.0    7    0.0
h  NaN    8    NaN

In [15]:
del df['One']
df

Two  Three
a    1    0.0
b    2    0.0
c    3    0.0
d    4    0.0
e    5    0.0
f    6    0.0
g    7    0.0
h    8    NaN

#loc and iloc

In [16]:
x = [10,20,30,40,50]
print(x[2])

30


In [21]:
data = pd.Series(['a','b','c','d'], index = [1,3,5,7])
print(data)
print(data.loc[5])
print(data.iloc[2])

1    a
3    b
5    c
7    d
dtype: object
c
c


#Additonal Functions


In [22]:
data = {"Name":['A','B','C','D'],'Age':['25','21','62','41']}
df = pd.DataFrame(data)
print(df.dtypes)
df

Name    object
Age     object
dtype: object


Name Age
0    A  25
1    B  21
2    C  62
3    D  41

In [23]:
#astype --> convert one datatype into another datatype

df['Age'] = df['Age'].astype(int)
print(df.dtypes)
df

Name    object
Age      int64
dtype: object


Name  Age
0    A   25
1    B   21
2    C   62
3    D   41

In [24]:
df.describe()

Age
count   4.000000
mean   37.250000
std    18.625699
min    21.000000
25%    24.000000
50%    33.000000
75%    46.250000
max    62.000000

In [26]:
data = {'Name':['A','B',np.nan,'D'], 'Age':[25,np.nan,62,41]}
df = pd.DataFrame(data)
df

Name   Age
0    A  25.0
1    B   NaN
2  NaN  62.0
3    D  41.0

In [27]:
df1 = df.dropna()
df1


Name   Age
0    A  25.0
3    D  41.0

In [28]:
df1 = df.fillna(0)
df1

Name   Age
0    A  25.0
1    B   0.0
2    0  62.0
3    D  41.0

In [33]:
data = {"Name":['A','B','C','D'],'Age':[25,21,62,41]}
df = pd.DataFrame(data)

df['Age'].replace(25,30, inplace=True)
df


<ipython-input-33-c146ceb56342>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].replace(25,30, inplace=True)


Name  Age
0    A   30
1    B   21
2    C   62
3    D   41

#   Wroking with CSV files
    #open empty Excel file
    #Click on file -> Save as -> (Choose the location of the current .py file)
    #Create a file name & choose the type as CSV (comma delimited)
    #Enter some values in the file

In [34]:
df = pd.read_csv('example1.csv')
df

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [35]:
df.head() #generates first 5 rows

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [36]:
df.tail() #generates lsat five rows

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [37]:
df

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [38]:
df.apply(np.max)

ROLLNO    105
NAME        E
dtype: object

In [39]:
df.apply(np.min)

ROLLNO    101
NAME        A
dtype: object

In [40]:
df.sort_values(by = 'NAME')

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [44]:
df.loc[df.ROLLNO == 104]

ROLLNO NAME
3     104    D

In [51]:
df.loc[(df.ROLLNO > 102) & (df.ROLLNO < 105),["NAME","ROLLNO"]]

NAME  ROLLNO
2    C     103
3    D     104